### ISSUE TITLE
Rename vehicles.txt

### ISSUE THREAD

**Issue by bhargavasana** [sfcta/NetworkWrangler#10]
vehicles.txt needs to be renamed to vehicles_ft.txt as per standards. Fast-trips is looking for vehicles_ft.txt too.

**Comment by bhargavasana** [comment]
Please also rename walk_access.txt to walk_access_ft.txt

**Comment by bhargavasana** [comment]
Please also rename drive_access.txt to drive_access_ft.txt

**Comment by sdrewc** [comment]
closed by #15
