### ISSUE TITLE
Issue with stop ids in walk_access_ft.txt

### ISSUE THREAD

**Issue by bhargavasana** [sfcta/NetworkWrangler#12]
Some stop ids in walk_access_ft.txt are cannot be found in stops.txt. Example: stop_id 15067 is in walk access file but not in stops file.

**Comment by sdrewc** [comment]
Closed by #15

**Comment by bhargavasana** [comment]
There are still some stop ids hanging in walk_access_ft.txt that cannot be found in stops.txt. For example:
15475, 15621, 24251, 15455 etc.

**Comment by sdrewc** [comment]
closed by #22
