### ISSUE TITLE
drive_access_points_ft.txt file is missing

### ISSUE THREAD

**Issue by bhargavasana** [sfcta/NetworkWrangler#14]
FT seems to be looking for drive_access_points_ft.txt  since it found drive_access.txt. This file should atleast have the "drop_off" and "capacity" columns present in it. drop_off is being used to determine whether a parking lot is pnr or knr.

**Comment by bhargavasana** [comment]
There is a statement that says -  In order to be connected to the transit system, drive access points must be connected to transit stops in transfers_ft.txt. Just want to confirm that this is being done.

https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/drive_access_points_ft.md

**Comment by sdrewc** [comment]
closed by #15.  pnr.txt renamed to drive_access_points_ft.txt.  This file now contains all mandatory fields, but no optional fields.  "drop_off" and "capacity" are NOT included (and not mandatory).
