### ISSUE TITLE
High speed travel detected by GTFS loader/validator

### ISSUE THREAD

**Issue by bhargavasana** [sfcta/NetworkWrangler#17]
It appears like I never reported this issue formally on github. Some examples:

High speed travel detected in trip 13820: 102700 to 13839. 61 meters in 0
seconds.
High speed travel detected in trip 16539: 5085 to 5083. 521 meters in 15
seconds. (125 km/h).
High speed travel detected in trip 29681: 14708 to 14707. 839 meters in 2
seconds. (1510 km/h).
High speed travel detected in trip 29680: 14784 to 14785. 1262 meters in 1
seconds. (4542 km/h).
High speed travel detected in trip 29686: 14705 to 14704. 1147 meters in 2
seconds. (2065 km/h).

**Comment by e-lo** [comment]
Is this from the test network ? Aka for @sdrewc ?

**Comment by sdrewc** [comment]
@e-lo It is the full San Francisco network, and yes it is for me.

**Comment by e-lo** [comment]
10-4

**Comment by sdrewc** [comment]
The travel time calculations should be correct as of #22 although there may be some instances where a segment's coded distance is shorter than its geometric distance (ex. a freeway underpass segment) that might still result in high speeds.  Hopefully these should smooth out over a stop-to-stop distance and you should stop seeing these errors.  Let me know if not.
