### ISSUE TITLE
High distance values in transfers_ft.txt

### ISSUE THREAD

**Issue by bhargavasana** [sfcta/NetworkWrangler#20]
There are some records with distance over 4 miles, we might want to check those. A handful of records have distance over 10 miles! Maybe there are some special cases to deal with.

**Comment by e-lo** [comment]
Is this a "factored distance" based on generalized cost or true distance? [ in which case it shouldn't have been generated by Cube ]

**Comment by sdrewc** [comment]
closed by #23
